# k8s/secret-jwt.yaml
apiVersion: v1
kind: Secret
metadata:
  name: auth-jwt
  namespace: greetings
type: Opaque
stringData:
  active.pem: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAumrYVsivb6uyO2DJkXGVKmVeQtkJc+yqfH0rOKSeoP/h66WT
    EfwA8uDtltoW1BEHltXX6NcBUVSubpVX4Br7yqJurSKJChVy8emwJiPmfznSkao1
    L4UrPdlMlOWiij/c8JTjPwfkCLYuo3EU27C+koDELQ1I72m/hNQuhVfT7i7z6jIF
    jvn6C+asLbNi6YYYNH5jug4YD8CLh1aXzzr3tquG60sqLyZGZijvFeHXlauOsBb1
    +NgJMexFSysk2xPtBBsHhrtGMsfqGarPZLhpHZUeTXl4iGqFMmxShNo567KLdfwq
    fFmTJvT+Sut4ifqyEK6PfyaBLg3XSCHZ53cSwwIDAQABAoIBAFHK3X8+cJNLv1kE
    P4y8TFmcvn4QInClr6wNc3BX8m3rt+Gf9WaXrobin/xnVkrX6f+JdkFoTOC1ig9l
    IXhn/oBLQspec8hj3to70Zj6eYDrCvP0vX9LK8zoUgymsOl92eAJQ6f9O1WDMfVu
    gVtfMk6vhuPJh23cdTa/rmW9QnSnj4pDiQWYWZwkCHJuIHiU+GcLKevwuxFbXVPx
    rahAMUzQxCeu9ZduMN3/ZUj8FzaWfngPBPQeuDJiQtk5dNZusEod85X8w85CYjqc
    gE1CqFKfVs1ZPsT673L/3FiTxQq0auXDs4YYHM7iW8yO3XhFbLqgCEVfkaYILyAU
    Jh087LECgYEA3umsUgFEJFzWNXYFW1JKGvRrN/e48jSNlmQNh0zbgkf0vEqJFR3L
    fOyMfqhoTLctG3ATRazpbS7iyxhmMTBIQvBr7SABCYOf9JRnBhEsQ8zEn/mF7fQ0
    vF3LkgEol8onar/9ETeHAo/i41rOc5RSoTU5ycjUDkZF6BmJvpqVjKkCgYEA1hZn
    mTWBxzipBpm1NxAl8jFhVnuThVQ/HyEs5kr2lC7Dvs9YcHFR4a4ZgxfqX/FTcvyp
    DtxkTTZW+6iTzs06FphHt7JM2+2pNJ+ntA0AhJmP7TTIPvcoj10UESAY5DHJd/4K
    oBFk78UdURFVK0jxcVYhQ9WkvwKUdPiPhcrK+4sCgYEAlp74RBT88UEVsNwFdJZe
    4mXDSPcHLgmankMO7RxeumJamRwYEn+mbsv7ht3OU//157NMImla9N6YejkLXDNO
    sIR5uKlGaiJZY88e6feSnGFxftMAzy+SrrEGC6riveXnynbdzdNiU7XbzloeY/SV
    /L3VRWaA+wA63kDbVUJoyLkCgYEAqxx7LyRqFu49gq4F/f2lJp+7OeFJdm5wiRP+
    DA7saGG8SFz3Rd/83xFFCNdrl8WNukEhamRSsrf06+3APbEgdYC/CZ6z+bBJ5mqZ
    IrqlqFYIiEIArvri6zss18c8vd7hNUvR+EAO2elFVk8xMIh7meeKbOpsY9LPD3K/
    W+NLO6MCgYAyyZ0DNZ8cAjhYuzpRF9bInJsPHUkcYmx/pRTZL2WpoGPfB1PF+pwC
    7J5etLRPyT4A3ta4eY2gCIWWmo5zVjlKfCKslBs9kepgmngDiBgES/YrsLIl1DkQ
    0q4e1K+iPhgKPx4hYJPHo24pKhUecC00GE/GQaHEtExXaw3TtoKZ7Q==
    -----END RSA PRIVATE KEY-----

  next.pem: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAv4N9Mxo12cqyuXaDkT5WzG0eWBvRS+WANkzn4rLaxjB1vomw
    V9vzYtD2/EJvAHxS+b+K1g3J//gwnwon1194snq1e/RnB9LIfvB2a9I3R3pkOz1h
    rpubHgAhqes6tERjd4tdWn80GNjdhfvVUmvQGEff4xTaTpYdIgz1kRtrtG52zsnW
    271D5BeO2XgI2Iq5SpNp7uK+iJCKM+5qQ9e2IMOwaxdK77QQbOTSg5oxUonL4/l+
    C4cL2M8mivH+KFd2rmTk5MkL/RwSpJpspzZrQchPDtDmZB12JZk46ocMoRYH5nHr
    yFidvLH/jPszrfuuI7n9jb50Ofa06Ra9WhU2ewIDAQABAoIBAQCKkB8wryERP+gJ
    6eaNWtZAOB8BTrciu50FLKWFzzQcuwkl38c3+krhTyG0KHjZmBoM2vofn4Bsc+zx
    1M44tLnGIKRYV9+HuIkZ1u9HWaRnUfVdKy8Wvzz++sdggnJJ5UU2RB46ENjntVip
    zSht5tV8C9zAFuFQhKn1bfzqjTVjKFxu50lTYbojZGKqjIvcahu8EDq9lenyJ3Q1
    NTYF4urqW0qHvB1jWpc6iRxH/Fzh0s/ieQiitR/Vz60NWqH9d+rPDymOsPJ0OCgP
    J4eqFj4QnZO5i4Exoho9tfX1zHj9Bz7oaiGPQf8ELGcOvam4PbN0p0DUgoUoDrJt
    fX1q8bYBAoGBAOmEmbhuxdpssD7UNGtnHiKfqBwNDmwIzfkaCuy9wR9tCL4ORxkm
    tFw3LhIbsCPI0v9NliBlaOoN4hOeRJT2OZ3edWBDOPmxP+AoiYOfvb7diFfxZZn3
    46BLQ/SOjIzGfH0wDjLtN/NWGep0QoVo6H0WbikDO12aL1vGUHk9Qq8BAoGBANHz
    oPiR/01oXABl2BJr4TF/IPnPtQWc4+98lXQJkXKBndH60dGiK4YTUi0jr07efqhS
    Sst4L2JMlsBkKY0x9ILqbwErIpCMg6BqXuM+XjOlUygVFPzTb2uSK5FRDd8yJxBS
    MOWcXiF2QmqsgzqkVh+d8J5U+B3s/UDv2jiOfCF7AoGBAKJ0XmDhp4GKZZ6AEKu7
    hEqAGfrR1nuwMGMhDAKhDC6psxBNbIcB1y3kMYflfUeX2bpFJrEI+9EAsYwGah3b
    oj/C2JOMkKGc/xwZ93j7c4zKH6VWyeEwhEoqsm77kKoLF+YbvXUOdQMznjnugazA
    TCVhqmeb2PwIXPQS5j9CMBcBAoGBAMqfNt5OgLcjHY9gutxkcwxC5f9R/yFwneaW
    NOKtDUsWXsq1J2QK/7hA01EvHFSglFo8OWUPE6PpyJ/ayuMysAjc2c6l45Dfm3To
    07S6j02Go6+OURgDsod9pUB0mk+q5lpxCDHA7HOc31J2NZwV1+xhkEQuOtseyfeu
    w8tLb+8bAoGABUDNXA+fzlZg1Ja2E4q+wL8UGwbDc8RfNyZ+FnMdGaPb64ALcDeh
    cKTI8dihH5Oo2Ltds2xTg8lZfYi4HRKSuqMM938YO1WpatoEzGexK6fXRp+ewyfx
    3e2enb1u26xFMCM5iGpzQbGEgbZbKgLbUmOqxfJcadKSI4/JazhD/uo=
    -----END RSA PRIVATE KEY-----
