name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  GO_VERSION: "1.23.x"
  IMAGE_NAME: ghcr.io/${{ github.repository }}/auth-service

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build linux amd64
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/auth-linux-amd64 ./cmd/server
      - uses: actions/upload-artifact@v4
        with:
          name: auth-binaries
          path: dist/*
      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Generate swagger and check diff
        run: |
          swag init -g cmd/server/main.go -o docs
          if ! git diff --exit-code -- docs; then
            echo "Swagger docs out of date. Run 'swag init' locally and commit." && exit 1
          fi

  docker-tag:
    runs-on: ubuntu-latest
    needs: build-binaries
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build & push tag
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
